### ISSUE TITLE
Make a release 0.0.1

### ISSUE THREAD

**Issue by Lihhhhwc** [Lihhhhwc/Template#3]
* Python Template Package version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by NRajaL** [comment]
Fixed issue 3 with release

22e61a1d074e7d5f9d955aa9c8a5aed717ceef92
